services:
  postgres:
    image: postgres:18.1
    container_name: prism_postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.20-alpine
    container_name: prism_flyway
    command: migrate
    volumes:
      - ./postgres-migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_BASELINE_ON_MIGRATE: "true"
      FLYWAY_SCHEMAS: public
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  assignment-cache:
    image: redis:8.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - assignment-cache:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    env_file:
      - .env
    volumes:
      - ./kafka/kafka-init.sh:/kafka-init.sh
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "/etc/confluent/docker/run & sleep 10 && bash /kafka-init.sh && wait",
      ]

  admin-service:
    image: admin-service
    container_name: prism_admin_service
    ports:
      - "${ADMIN_SERVICE_HTTP_PORT}:${ADMIN_SERVICE_HTTP_PORT}"
      - "${ADMIN_SERVICE_GRPC_SERVER_PORT}:${ADMIN_SERVICE_GRPC_SERVER_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      ADMIN_SERVICE_GRPC_SERVER_ADDRESS: 0.0.0.0
    depends_on:
      flyway:
        condition: service_completed_successfully
      kafka:
        condition: service_started

  assignment-service:
    image: assignment-service
    container_name: prism_assignment_service
    ports:
      - "${ASSIGNMENT_SERVICE_HTTP_PORT}:${ASSIGNMENT_SERVICE_HTTP_PORT}"
    env_file:
      - .env
    environment:
      REDIS_HOST: assignment-cache
      KAFKA_BOOTSTRAP_SERVER_HOST: kafka
      KAFKA_BOOTSTRAP_SERVER_PORT: 29092
      ADMIN_SERVICE_GRPC_SERVER_ADDRESS: admin-service
    depends_on:
      admin-service:
        condition: service_started
      assignment-cache:
        condition: service_started
      kafka:
        condition: service_started

  events-service:
    image: events-service
    container_name: prism_events_service
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      GRPC_SERVER_HOST: admin-service
      GRPC_SERVER_PORT: ${ADMIN_SERVICE_GRPC_SERVER_PORT}
    depends_on:
      admin-service:
        condition: service_started
      kafka:
        condition: service_started

volumes:
  postgres_data:
  assignment-cache:
    driver: local
