spring:
  application:
    name: events-service

server:
  port: 5678

grpc:
    server:
        port: 50052
        host: localhost

logging:
  level:
    root: INFO
    org.prism.eventsservice: DEBUG
